using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GloryFlorence.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class InitialMigration_20260913 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AppointmentTypes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(100) NOT NULL,
                    ""DurationMinutes"" integer NOT NULL DEFAULT 30,
                    ""Description"" character varying(500) NOT NULL,
                    ""IsActive"" boolean NOT NULL DEFAULT TRUE,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_AppointmentTypes"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""BloodGroups"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(10) NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_BloodGroups"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Categories"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(100) NOT NULL,
                    ""Description"" character varying(500) NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_Categories"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""ClinicSettings"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ClinicName"" text NOT NULL,
                    ""Tagline"" text NULL,
                    ""Email"" text NULL,
                    ""Phone"" text NULL,
                    ""Address"" text NULL,
                    ""City"" text NULL,
                    ""State"" text NULL,
                    ""Country"" text NULL,
                    ""PostalCode"" text NULL,
                    ""TaxRegistrationNumber"" text NULL,
                    ""CurrencySymbol"" text NULL,
                    ""WorkingHoursStart"" interval NOT NULL,
                    ""WorkingHoursEnd"" interval NOT NULL,
                    ""AppointmentSlotDurationMinutes"" integer NOT NULL,
                    ""AutoConfirmAppointments"" boolean NOT NULL,
                    ""EnableSmsNotifications"" boolean NOT NULL,
                    ""EnableEmailNotifications"" boolean NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_ClinicSettings"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Countries"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(100) NOT NULL,
                    ""Code"" character varying(10) NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_Countries"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Genders"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(50) NOT NULL,
                    ""Code"" character varying(10) NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_Genders"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Patients"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""MRN"" character varying(50) NOT NULL DEFAULT '',
                    ""FirstName"" character varying(50) NOT NULL,
                    ""LastName"" character varying(50) NOT NULL,
                    ""DateOfBirth"" timestamp with time zone NOT NULL,
                    ""Gender"" character varying(10) NOT NULL,
                    ""BloodGroup"" character varying(20) NOT NULL DEFAULT '',
                    ""Email"" character varying(100) NOT NULL,
                    ""PhoneNumber"" character varying(20) NOT NULL,
                    ""Address"" character varying(250) NOT NULL,
                    ""City"" character varying(100) NOT NULL DEFAULT '',
                    ""State"" character varying(100) NOT NULL DEFAULT '',
                    ""Country"" character varying(100) NOT NULL DEFAULT '',
                    ""EmergencyContactName"" character varying(100) NOT NULL DEFAULT '',
                    ""EmergencyContactPhone"" character varying(50) NOT NULL DEFAULT '',
                    ""Status"" character varying(50) NOT NULL DEFAULT 'Active',
                    ""MedicalHistory"" character varying(2000) NOT NULL,
                    ""BloodPressure"" character varying(20) NULL,
                    ""HeartRate"" integer NULL,
                    ""WeightKg"" double precision NULL,
                    ""HeightCm"" double precision NULL,
                    ""Temperature"" double precision NULL,
                    ""OxygenSaturation"" double precision NULL,
                    ""VitalsUpdatedAt"" timestamp with time zone NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Patients"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Roles"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(50) NOT NULL,
                    ""Description"" character varying(200) NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Roles"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Specializations"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(100) NOT NULL,
                    ""Description"" character varying(500) NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Specializations"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Statuses"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Type"" character varying(50) NOT NULL,
                    ""Code"" character varying(50) NOT NULL,
                    ""Name"" character varying(50) NOT NULL,
                    ""Description"" character varying(200) NULL,
                    ""DisplayOrder"" integer NOT NULL DEFAULT 0,
                    ""IsActive"" boolean NOT NULL DEFAULT TRUE,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Statuses"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Therapists"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""FirstName"" character varying(50) NOT NULL,
                    ""LastName"" character varying(50) NOT NULL,
                    ""Specialization"" character varying(100) NOT NULL,
                    ""Email"" character varying(100) NOT NULL,
                    ""PhoneNumber"" character varying(20) NOT NULL,
                    ""LicenseNumber"" character varying(50) NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Therapists"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Users"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Username"" character varying(50) NOT NULL,
                    ""Email"" character varying(100) NOT NULL,
                    ""PasswordHash"" character varying(250) NOT NULL,
                    ""FirstName"" character varying(50) NOT NULL,
                    ""LastName"" character varying(50) NOT NULL,
                    ""Role"" character varying(20) NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""RefreshToken"" character varying(250) NULL,
                    ""RefreshTokenExpiryTime"" timestamp with time zone NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Users"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Exercises"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""CategoryId"" integer NOT NULL,
                    ""Name"" character varying(100) NOT NULL,
                    ""Description"" character varying(500) NOT NULL,
                    ""Instructions"" character varying(2000) NOT NULL,
                    ""VideoUrl"" character varying(500) NOT NULL,
                    ""ImageUrl"" character varying(500) NOT NULL,
                    ""IsActive"" boolean NOT NULL DEFAULT TRUE,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Exercises"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Exercises_Categories_CategoryId"" FOREIGN KEY (""CategoryId"") REFERENCES ""Categories"" (""Id"") ON DELETE RESTRICT
                );

                CREATE TABLE IF NOT EXISTS ""TreatmentTypes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""CategoryId"" integer NOT NULL,
                    ""Name"" character varying(100) NOT NULL,
                    ""Description"" character varying(500) NOT NULL,
                    ""DefaultDurationMinutes"" integer NOT NULL DEFAULT 30,
                    ""DefaultPrice"" numeric(18,2) NOT NULL DEFAULT 0.0,
                    ""IsActive"" boolean NOT NULL DEFAULT TRUE,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_TreatmentTypes"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_TreatmentTypes_Categories_CategoryId"" FOREIGN KEY (""CategoryId"") REFERENCES ""Categories"" (""Id"") ON DELETE RESTRICT
                );

                CREATE TABLE IF NOT EXISTS ""States"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(100) NOT NULL,
                    ""CountryId"" integer NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_States"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_States_Countries_CountryId"" FOREIGN KEY (""CountryId"") REFERENCES ""Countries"" (""Id"") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS ""Invoices"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""InvoiceNumber"" text NOT NULL,
                    ""PatientId"" integer NOT NULL,
                    ""SubTotal"" numeric NOT NULL DEFAULT 0,
                    ""TaxAmount"" numeric NOT NULL DEFAULT 0,
                    ""DiscountAmount"" numeric NOT NULL DEFAULT 0,
                    ""TotalAmount"" numeric NOT NULL DEFAULT 0,
                    ""Amount"" numeric NOT NULL,
                    ""PaidAmount"" numeric NOT NULL,
                    ""BalanceAmount"" numeric NOT NULL,
                    ""Status"" text NOT NULL,
                    ""InvoiceDate"" timestamp with time zone NOT NULL,
                    ""DueDate"" timestamp with time zone NULL,
                    ""Notes"" text NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Invoices"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Invoices_Patients_PatientId"" FOREIGN KEY (""PatientId"") REFERENCES ""Patients"" (""Id"") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS ""PatientDocuments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PatientId"" integer NOT NULL,
                    ""DocumentName"" character varying(250) NOT NULL,
                    ""DocumentType"" character varying(100) NOT NULL,
                    ""FilePath"" character varying(500) NOT NULL,
                    ""FileSize"" bigint NOT NULL,
                    ""UploadedAt"" timestamp with time zone NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_PatientDocuments"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_PatientDocuments_Patients_PatientId"" FOREIGN KEY (""PatientId"") REFERENCES ""Patients"" (""Id"") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS ""PatientMedicalHistory"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PatientId"" integer NOT NULL,
                    ""Diagnosis"" character varying(250) NOT NULL,
                    ""Symptoms"" character varying(500) NOT NULL,
                    ""TreatmentReceived"" character varying(500) NOT NULL,
                    ""RecordDate"" timestamp with time zone NOT NULL,
                    ""Remarks"" character varying(500) NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_PatientMedicalHistory"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_PatientMedicalHistory_Patients_PatientId"" FOREIGN KEY (""PatientId"") REFERENCES ""Patients"" (""Id"") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS ""Appointments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PatientId"" integer NOT NULL,
                    ""PhysiotherapistId"" integer NOT NULL,
                    ""AppointmentTypeId"" integer NOT NULL,
                    ""AppointmentDate"" timestamp with time zone NOT NULL,
                    ""StartTime"" interval NOT NULL,
                    ""EndTime"" interval NOT NULL,
                    ""Status"" character varying(50) NOT NULL DEFAULT 'Scheduled',
                    ""Reason"" character varying(250) NOT NULL,
                    ""Notes"" character varying(1000) NOT NULL,
                    ""CancellationReason"" character varying(500) NULL,
                    ""Room"" text NULL,
                    ""Fee"" numeric NULL,
                    ""TherapistId"" integer NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Appointments"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Appointments_AppointmentTypes_AppointmentTypeId"" FOREIGN KEY (""AppointmentTypeId"") REFERENCES ""AppointmentTypes"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Appointments_Patients_PatientId"" FOREIGN KEY (""PatientId"") REFERENCES ""Patients"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Appointments_Therapists_TherapistId"" FOREIGN KEY (""TherapistId"") REFERENCES ""Therapists"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Appointments_Users_PhysiotherapistId"" FOREIGN KEY (""PhysiotherapistId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );

                CREATE TABLE IF NOT EXISTS ""AuditLogs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NULL,
                    ""Action"" character varying(100) NOT NULL,
                    ""EntityName"" character varying(100) NOT NULL,
                    ""EntityId"" character varying(100) NOT NULL,
                    ""OldValue"" character varying(4000) NULL,
                    ""NewValue"" character varying(4000) NULL,
                    ""IPAddress"" character varying(50) NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_AuditLogs"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_AuditLogs_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE SET NULL
                );

                CREATE TABLE IF NOT EXISTS ""UserProfiles"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NOT NULL,
                    ""PhoneNumber"" character varying(20) NULL,
                    ""DateOfBirth"" timestamp with time zone NULL,
                    ""Gender"" character varying(15) NULL,
                    ""Address"" character varying(250) NULL,
                    ""Bio"" character varying(500) NULL,
                    ""ProfilePictureUrl"" character varying(500) NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_UserProfiles"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_UserProfiles_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS ""UserRoles"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NOT NULL,
                    ""RoleId"" integer NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_UserRoles"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_UserRoles_Roles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""Roles"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_UserRoles_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS ""Cities"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(100) NOT NULL,
                    ""StateId"" integer NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Cities"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Cities_States_StateId"" FOREIGN KEY (""StateId"") REFERENCES ""States"" (""Id"") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS ""InvoiceItems"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""InvoiceId"" integer NOT NULL,
                    ""TreatmentTypeId"" integer NULL,
                    ""Description"" text NOT NULL,
                    ""Quantity"" integer NOT NULL,
                    ""UnitPrice"" numeric NOT NULL,
                    ""TotalAmount"" numeric NOT NULL,
                    CONSTRAINT ""PK_InvoiceItems"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_InvoiceItems_Invoices_InvoiceId"" FOREIGN KEY (""InvoiceId"") REFERENCES ""Invoices"" (""Id"") ON DELETE CASCADE
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_InvoiceItems_TreatmentTypes_TreatmentTypeId') THEN
                        ALTER TABLE ""InvoiceItems"" ADD CONSTRAINT ""FK_InvoiceItems_TreatmentTypes_TreatmentTypeId"" FOREIGN KEY (""TreatmentTypeId"") REFERENCES ""TreatmentTypes"" (""Id"") ON DELETE RESTRICT;
                    END IF;
                END $$;

                CREATE TABLE IF NOT EXISTS ""Payments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""InvoiceId"" integer NOT NULL,
                    ""AmountPaid"" numeric NOT NULL,
                    ""PaymentMethod"" text NOT NULL,
                    ""TransactionReference"" text NULL,
                    ""PaymentDate"" timestamp with time zone NOT NULL,
                    ""Notes"" text NULL,
                    CONSTRAINT ""PK_Payments"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Payments_Invoices_InvoiceId"" FOREIGN KEY (""InvoiceId"") REFERENCES ""Invoices"" (""Id"") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS ""Addresses"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""StreetAddress"" character varying(250) NOT NULL,
                    ""CityId"" integer NOT NULL,
                    ""StateId"" integer NOT NULL,
                    ""CountryId"" integer NOT NULL,
                    ""PostalCode"" character varying(20) NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Addresses"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Addresses_Cities_CityId"" FOREIGN KEY (""CityId"") REFERENCES ""Cities"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_Addresses_Countries_CountryId"" FOREIGN KEY (""CountryId"") REFERENCES ""Countries"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_Addresses_States_StateId"" FOREIGN KEY (""StateId"") REFERENCES ""States"" (""Id"") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS ""PatientAssessments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PatientId"" integer NOT NULL,
                    ""PhysiotherapistId"" integer NOT NULL,
                    ""SessionId"" integer NULL,
                    ""AssessmentDate"" timestamp with time zone NOT NULL,
                    ""ChiefComplaint"" character varying(1000) NOT NULL,
                    ""CurrentCondition"" character varying(2000) NOT NULL,
                    ""PainLevel"" integer NOT NULL,
                    ""Diagnosis"" character varying(1000) NOT NULL,
                    ""ClinicalNotes"" character varying(2000) NOT NULL,
                    ""Recommendations"" character varying(1000) NOT NULL,
                    ""PainLocation"" text NULL,
                    ""PainType"" text NULL,
                    ""AggravatingFactors"" text NULL,
                    ""RelievingFactors"" text NULL,
                    ""RomFindings"" text NULL,
                    ""PostureAndGait"" text NULL,
                    ""FunctionalLimitations"" text NULL,
                    ""Prognosis"" text NULL,
                    ""ShortTermGoals"" text NULL,
                    ""LongTermGoals"" text NULL,
                    ""RecommendedFrequency"" text NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_PatientAssessments"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_PatientAssessments_Patients_PatientId"" FOREIGN KEY (""PatientId"") REFERENCES ""Patients"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_PatientAssessments_Users_PhysiotherapistId"" FOREIGN KEY (""PhysiotherapistId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );

                CREATE TABLE IF NOT EXISTS ""TreatmentPlans"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PatientId"" integer NOT NULL,
                    ""PhysiotherapistId"" integer NOT NULL,
                    ""AssessmentId"" integer NOT NULL,
                    ""StartDate"" timestamp with time zone NOT NULL,
                    ""ExpectedEndDate"" timestamp with time zone NOT NULL,
                    ""NumberOfSessions"" integer NOT NULL,
                    ""Goal"" character varying(500) NOT NULL,
                    ""Notes"" character varying(1000) NOT NULL,
                    ""Status"" character varying(50) NOT NULL DEFAULT 'Active',
                    ""Diagnosis"" text NULL,
                    ""TreatmentFrequency"" text NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_TreatmentPlans"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_TreatmentPlans_PatientAssessments_AssessmentId"" FOREIGN KEY (""AssessmentId"") REFERENCES ""PatientAssessments"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_TreatmentPlans_Patients_PatientId"" FOREIGN KEY (""PatientId"") REFERENCES ""Patients"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_TreatmentPlans_Users_PhysiotherapistId"" FOREIGN KEY (""PhysiotherapistId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );

                CREATE TABLE IF NOT EXISTS ""ExercisePrescriptions"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PatientId"" integer NOT NULL,
                    ""PhysiotherapistId"" integer NOT NULL,
                    ""TreatmentPlanId"" integer NOT NULL,
                    ""PrescriptionDate"" timestamp with time zone NOT NULL,
                    ""Instructions"" character varying(1000) NOT NULL,
                    ""Status"" character varying(50) NOT NULL DEFAULT 'Active',
                    ""Diagnosis"" text NULL,
                    ""TargetGoal"" text NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_ExercisePrescriptions"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ExercisePrescriptions_Patients_PatientId"" FOREIGN KEY (""PatientId"") REFERENCES ""Patients"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_ExercisePrescriptions_Users_PhysiotherapistId"" FOREIGN KEY (""PhysiotherapistId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ExercisePrescriptions_TreatmentPlans_TreatmentPlanId') THEN
                        ALTER TABLE ""ExercisePrescriptions"" ADD CONSTRAINT ""FK_ExercisePrescriptions_TreatmentPlans_TreatmentPlanId"" FOREIGN KEY (""TreatmentPlanId"") REFERENCES ""TreatmentPlans"" (""Id"") ON DELETE RESTRICT;
                    END IF;
                END $$;

                CREATE TABLE IF NOT EXISTS ""TreatmentSessions"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""AppointmentId"" integer NOT NULL,
                    ""PatientId"" integer NOT NULL,
                    ""PhysiotherapistId"" integer NOT NULL,
                    ""TreatmentPlanId"" integer NULL,
                    ""SessionDate"" timestamp with time zone NOT NULL,
                    ""StartTime"" interval NOT NULL,
                    ""EndTime"" interval NOT NULL,
                    ""PainLevelBefore"" integer NOT NULL,
                    ""PainLevelAfter"" integer NOT NULL,
                    ""Status"" character varying(50) NOT NULL DEFAULT 'Completed',
                    ""Assessment"" character varying(1000) NOT NULL,
                    ""TreatmentPerformed"" character varying(1000) NOT NULL,
                    ""Recommendations"" character varying(1000) NOT NULL,
                    ""Notes"" character varying(1000) NOT NULL,
                    ""ModalitiesConducted"" text NULL,
                    ""NextSessionPlan"" text NULL,
                    ""PatientTolerance"" text NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_TreatmentSessions"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_TreatmentSessions_Appointments_AppointmentId"" FOREIGN KEY (""AppointmentId"") REFERENCES ""Appointments"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_TreatmentSessions_Patients_PatientId"" FOREIGN KEY (""PatientId"") REFERENCES ""Patients"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_TreatmentSessions_Users_PhysiotherapistId"" FOREIGN KEY (""PhysiotherapistId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TreatmentSessions_TreatmentPlans_TreatmentPlanId') THEN
                        ALTER TABLE ""TreatmentSessions"" ADD CONSTRAINT ""FK_TreatmentSessions_TreatmentPlans_TreatmentPlanId"" FOREIGN KEY (""TreatmentPlanId"") REFERENCES ""TreatmentPlans"" (""Id"") ON DELETE RESTRICT;
                    END IF;
                END $$;

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_PatientAssessments_TreatmentSessions_SessionId') THEN
                        ALTER TABLE ""PatientAssessments"" ADD CONSTRAINT ""FK_PatientAssessments_TreatmentSessions_SessionId"" FOREIGN KEY (""SessionId"") REFERENCES ""TreatmentSessions"" (""Id"") ON DELETE RESTRICT;
                    END IF;
                END $$;

                CREATE TABLE IF NOT EXISTS ""ExercisePrescriptionDetails"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PrescriptionId"" integer NOT NULL,
                    ""ExerciseId"" integer NOT NULL,
                    ""Sets"" integer NOT NULL,
                    ""Repetitions"" integer NOT NULL,
                    ""HoldSeconds"" integer NOT NULL,
                    ""FrequencyPerDay"" integer NOT NULL,
                    ""DurationWeeks"" integer NOT NULL,
                    ""Instructions"" character varying(500) NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_ExercisePrescriptionDetails"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ExercisePrescriptionDetails_Exercises_ExerciseId"" FOREIGN KEY (""ExerciseId"") REFERENCES ""Exercises"" (""Id"") ON DELETE RESTRICT
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ExercisePrescriptionDetails_ExercisePrescriptions_PrescriptionId') THEN
                        ALTER TABLE ""ExercisePrescriptionDetails"" ADD CONSTRAINT ""FK_ExercisePrescriptionDetails_ExercisePrescriptions_PrescriptionId"" FOREIGN KEY (""PrescriptionId"") REFERENCES ""ExercisePrescriptions"" (""Id"") ON DELETE CASCADE;
                    END IF;
                END $$;

                CREATE TABLE IF NOT EXISTS ""TreatmentPlanDetails"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""TreatmentPlanId"" integer NOT NULL,
                    ""TreatmentTypeId"" integer NOT NULL,
                    ""Frequency"" character varying(50) NOT NULL,
                    ""DurationMinutes"" integer NOT NULL,
                    ""Instructions"" character varying(500) NOT NULL,
                    ""NumberOfSessions"" integer NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_TreatmentPlanDetails"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_TreatmentPlanDetails_TreatmentPlans_TreatmentPlanId"" FOREIGN KEY (""TreatmentPlanId"") REFERENCES ""TreatmentPlans"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_TreatmentPlanDetails_TreatmentTypes_TreatmentTypeId"" FOREIGN KEY (""TreatmentTypeId"") REFERENCES ""TreatmentTypes"" (""Id"") ON DELETE RESTRICT
                );

                -- INDEXES
                CREATE INDEX IF NOT EXISTS ""IX_Addresses_CityId"" ON ""Addresses"" (""CityId"");
                CREATE INDEX IF NOT EXISTS ""IX_Addresses_CountryId"" ON ""Addresses"" (""CountryId"");
                CREATE INDEX IF NOT EXISTS ""IX_Addresses_StateId"" ON ""Addresses"" (""StateId"");
                CREATE INDEX IF NOT EXISTS ""IX_Appointments_AppointmentTypeId"" ON ""Appointments"" (""AppointmentTypeId"");
                CREATE INDEX IF NOT EXISTS ""IX_Appointments_PatientId"" ON ""Appointments"" (""PatientId"");
                CREATE INDEX IF NOT EXISTS ""IX_Appointments_PhysiotherapistId"" ON ""Appointments"" (""PhysiotherapistId"");
                CREATE INDEX IF NOT EXISTS ""IX_Appointments_TherapistId"" ON ""Appointments"" (""TherapistId"");
                CREATE INDEX IF NOT EXISTS ""IX_AuditLogs_UserId"" ON ""AuditLogs"" (""UserId"");
                CREATE INDEX IF NOT EXISTS ""IX_Cities_StateId"" ON ""Cities"" (""StateId"");
                CREATE INDEX IF NOT EXISTS ""IX_ExercisePrescriptionDetails_ExerciseId"" ON ""ExercisePrescriptionDetails"" (""ExerciseId"");
                CREATE INDEX IF NOT EXISTS ""IX_ExercisePrescriptionDetails_PrescriptionId"" ON ""ExercisePrescriptionDetails"" (""PrescriptionId"");
                CREATE INDEX IF NOT EXISTS ""IX_ExercisePrescriptions_PatientId"" ON ""ExercisePrescriptions"" (""PatientId"");
                CREATE INDEX IF NOT EXISTS ""IX_ExercisePrescriptions_PhysiotherapistId"" ON ""ExercisePrescriptions"" (""PhysiotherapistId"");
                CREATE INDEX IF NOT EXISTS ""IX_ExercisePrescriptions_TreatmentPlanId"" ON ""ExercisePrescriptions"" (""TreatmentPlanId"");
                CREATE INDEX IF NOT EXISTS ""IX_Exercises_CategoryId"" ON ""Exercises"" (""CategoryId"");
                CREATE INDEX IF NOT EXISTS ""IX_InvoiceItems_InvoiceId"" ON ""InvoiceItems"" (""InvoiceId"");
                CREATE INDEX IF NOT EXISTS ""IX_InvoiceItems_TreatmentTypeId"" ON ""InvoiceItems"" (""TreatmentTypeId"");
                CREATE INDEX IF NOT EXISTS ""IX_Invoices_PatientId"" ON ""Invoices"" (""PatientId"");
                CREATE INDEX IF NOT EXISTS ""IX_PatientAssessments_PatientId"" ON ""PatientAssessments"" (""PatientId"");
                CREATE INDEX IF NOT EXISTS ""IX_PatientAssessments_PhysiotherapistId"" ON ""PatientAssessments"" (""PhysiotherapistId"");
                CREATE INDEX IF NOT EXISTS ""IX_PatientAssessments_SessionId"" ON ""PatientAssessments"" (""SessionId"");
                CREATE INDEX IF NOT EXISTS ""IX_PatientDocuments_PatientId"" ON ""PatientDocuments"" (""PatientId"");
                CREATE INDEX IF NOT EXISTS ""IX_PatientMedicalHistory_PatientId"" ON ""PatientMedicalHistory"" (""PatientId"");
                CREATE INDEX IF NOT EXISTS ""IX_Payments_InvoiceId"" ON ""Payments"" (""InvoiceId"");
                CREATE INDEX IF NOT EXISTS ""IX_States_CountryId"" ON ""States"" (""CountryId"");
                CREATE INDEX IF NOT EXISTS ""IX_TreatmentPlanDetails_TreatmentPlanId"" ON ""TreatmentPlanDetails"" (""TreatmentPlanId"");
                CREATE INDEX IF NOT EXISTS ""IX_TreatmentPlanDetails_TreatmentTypeId"" ON ""TreatmentPlanDetails"" (""TreatmentTypeId"");
                CREATE INDEX IF NOT EXISTS ""IX_TreatmentPlans_AssessmentId"" ON ""TreatmentPlans"" (""AssessmentId"");
                CREATE INDEX IF NOT EXISTS ""IX_TreatmentPlans_PatientId"" ON ""TreatmentPlans"" (""PatientId"");
                CREATE INDEX IF NOT EXISTS ""IX_TreatmentPlans_PhysiotherapistId"" ON ""TreatmentPlans"" (""PhysiotherapistId"");
                CREATE INDEX IF NOT EXISTS ""IX_TreatmentSessions_AppointmentId"" ON ""TreatmentSessions"" (""AppointmentId"");
                CREATE INDEX IF NOT EXISTS ""IX_TreatmentSessions_PatientId"" ON ""TreatmentSessions"" (""PatientId"");
                CREATE INDEX IF NOT EXISTS ""IX_TreatmentSessions_PhysiotherapistId"" ON ""TreatmentSessions"" (""PhysiotherapistId"");
                CREATE INDEX IF NOT EXISTS ""IX_TreatmentSessions_TreatmentPlanId"" ON ""TreatmentSessions"" (""TreatmentPlanId"");
                CREATE INDEX IF NOT EXISTS ""IX_TreatmentTypes_CategoryId"" ON ""TreatmentTypes"" (""CategoryId"");
                CREATE INDEX IF NOT EXISTS ""IX_UserProfiles_UserId"" ON ""UserProfiles"" (""UserId"");
                CREATE INDEX IF NOT EXISTS ""IX_UserRoles_RoleId"" ON ""UserRoles"" (""RoleId"");
                CREATE INDEX IF NOT EXISTS ""IX_UserRoles_UserId_RoleId"" ON ""UserRoles"" (""UserId"", ""RoleId"");
                CREATE INDEX IF NOT EXISTS ""IX_Users_Email"" ON ""Users"" (""Email"");
                CREATE INDEX IF NOT EXISTS ""IX_Users_Username"" ON ""Users"" (""Username"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
